### ISSUE TITLE
docs(graphql*compodoc*github): add documentaion [WiP]

### ISSUE THREAD

**Issue by DennyTim** [DennyTim/modern-app#16]
На данном этапе необходимо выполнить следующее: 

 - [ ] - добавить комментарии к файлам graphql
 - [ ] - добавить генерацию документации для приложений
 - [ ] - настройка compodoc | Nx документация
 - [ ] - решить проблему нескольких приложений и README.md в корне репозитория
 - [ ] - настроить скрипты
 - [ ] - добавить документацию на github page
 - [ ] - настроить экшен для автогенерации документации

 ```yml
 name: Generate documentation
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Copy branch [master]
        uses: actions/checkout@v2
      - 
        name: Install NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - 
        name: Install dependencies
        run: npm install      
      - 
        name: Run compodoc
        run: npx nx affected --all --target=compodoc    
      - 
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GH_PAGE }}
```
